version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: projeto-02
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=projeto